/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package App;

import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Cursor;
import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.SwingUtilities;

/**
 *
 * @author asus
 */
public class TeamGuide extends javax.swing.JFrame {
    private int userId;
    private String username;
    private String email;
    private ArrayList<String> elements = new ArrayList<>();
    private ArrayList<String> weapons = new ArrayList<>();
    /**
     * Creates new form TeamGuide
     */
    public TeamGuide() {
        initComponents();
        this.userId = 1;
        setLocationRelativeTo(null);
        myinit();
    }
    
    public TeamGuide(int userId, String username, String email) {
        initComponents();
        this.userId = userId;
        this.username = username;
        this.email = email;
        setLocationRelativeTo(null);
        myinit();
    }
    
    private void myinit(){
        usernameLabel.setText(username);
        emailLabel.setText(email);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        parentPanel = new javax.swing.JPanel();
        teamPage1 = new javax.swing.JPanel();
        profileButton = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        exitButton = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        enemiesPane = new javax.swing.JPanel();
        scrollPane = new javax.swing.JScrollPane();
        clonePanelContainer = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        modeSpiralAbyss = new javax.swing.JRadioButton();
        hydroRadButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        modeEnemyOnly = new javax.swing.JRadioButton();
        swordRadButton = new javax.swing.JRadioButton();
        dendroRadButton = new javax.swing.JRadioButton();
        electroRadButton = new javax.swing.JRadioButton();
        geoRadButton = new javax.swing.JRadioButton();
        physicalRadButton = new javax.swing.JRadioButton();
        cryoRadButton = new javax.swing.JRadioButton();
        anemoRadButton = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        bowRadButton = new javax.swing.JRadioButton();
        polearmRadButton = new javax.swing.JRadioButton();
        catalystRadButton = new javax.swing.JRadioButton();
        claymoreRadButton = new javax.swing.JRadioButton();
        pyroRadButton = new javax.swing.JRadioButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        nextLabel = new javax.swing.JLabel();
        nextButton = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Team Guide Page");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(1280, 720));
        setPreferredSize(new java.awt.Dimension(1290, 750));
        setResizable(false);
        getContentPane().setLayout(null);

        parentPanel.setLayout(new java.awt.CardLayout());

        teamPage1.setLayout(null);

        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/profile1.png"))); // NOI18N
        profileButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profileButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profileButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profileButtonMouseExited(evt);
            }
        });
        teamPage1.add(profileButton);
        profileButton.setBounds(30, 15, 70, 70);

        usernameLabel.setFont(new java.awt.Font("Sunflower Medium", 0, 30)); // NOI18N
        usernameLabel.setForeground(new java.awt.Color(252, 236, 214));
        usernameLabel.setText("Username");
        teamPage1.add(usernameLabel);
        usernameLabel.setBounds(110, 25, 131, 40);

        emailLabel.setFont(new java.awt.Font("Sunflower Medium", 0, 20)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(252, 236, 214));
        emailLabel.setText("Email@gmail.com");
        teamPage1.add(emailLabel);
        emailLabel.setBounds(110, 60, 158, 26);

        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/exit1.png"))); // NOI18N
        exitButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                exitButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                exitButtonMouseExited(evt);
            }
        });
        teamPage1.add(exitButton);
        exitButton.setBounds(1190, 20, 70, 70);

        jLabel2.setFont(new java.awt.Font("HYWenHei-85W", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(241, 167, 84));
        jLabel2.setText("(optional)");
        jLabel2.setToolTipText("");
        teamPage1.add(jLabel2);
        jLabel2.setBounds(990, 240, 90, 30);

        enemiesPane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        clonePanelContainer.setBackground(new java.awt.Color(255, 204, 204));
        clonePanelContainer.setPreferredSize(new java.awt.Dimension(400, 200));
        clonePanelContainer.setLayout(null);
        scrollPane.setViewportView(clonePanelContainer);

        enemiesPane.add(scrollPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 470));

        teamPage1.add(enemiesPane);
        enemiesPane.setBounds(55, 172, 500, 470);

        jLabel3.setFont(new java.awt.Font("HYWenHei-85W", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 167, 84));
        jLabel3.setText("Select Enemies");
        jLabel3.setToolTipText("");
        teamPage1.add(jLabel3);
        jLabel3.setBounds(55, 120, 280, 40);

        modeSpiralAbyss.setFont(new java.awt.Font("HYWenHei-85W", 0, 24)); // NOI18N
        modeSpiralAbyss.setForeground(new java.awt.Color(252, 236, 214));
        modeSpiralAbyss.setText("Spiral Abyss");
        modeSpiralAbyss.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modeSpiralAbyss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        teamPage1.add(modeSpiralAbyss);
        modeSpiralAbyss.setBounds(850, 150, 220, 35);

        hydroRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        hydroRadButton.setForeground(new java.awt.Color(252, 236, 214));
        hydroRadButton.setText("Hydro");
        hydroRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hydroRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        hydroRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                hydroRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                hydroRadButtonMouseExited(evt);
            }
        });
        hydroRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hydroRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(hydroRadButton);
        hydroRadButton.setBounds(910, 290, 120, 33);

        jLabel4.setFont(new java.awt.Font("HYWenHei-85W", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(241, 167, 84));
        jLabel4.setText("Modes");
        jLabel4.setToolTipText("");
        teamPage1.add(jLabel4);
        jLabel4.setBounds(611, 92, 280, 40);

        modeEnemyOnly.setFont(new java.awt.Font("HYWenHei-85W", 0, 24)); // NOI18N
        modeEnemyOnly.setForeground(new java.awt.Color(252, 236, 214));
        modeEnemyOnly.setText("Enemies only");
        modeEnemyOnly.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        modeEnemyOnly.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        teamPage1.add(modeEnemyOnly);
        modeEnemyOnly.setBounds(615, 150, 220, 35);

        swordRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        swordRadButton.setForeground(new java.awt.Color(252, 236, 214));
        swordRadButton.setText("Sword");
        swordRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        swordRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        swordRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                swordRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                swordRadButtonMouseExited(evt);
            }
        });
        swordRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                swordRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(swordRadButton);
        swordRadButton.setBounds(620, 480, 120, 33);

        dendroRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        dendroRadButton.setForeground(new java.awt.Color(252, 236, 214));
        dendroRadButton.setText("Dendro");
        dendroRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        dendroRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        dendroRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dendroRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dendroRadButtonMouseExited(evt);
            }
        });
        dendroRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dendroRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(dendroRadButton);
        dendroRadButton.setBounds(1060, 290, 120, 33);

        electroRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        electroRadButton.setForeground(new java.awt.Color(252, 236, 214));
        electroRadButton.setText("Electro");
        electroRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        electroRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        electroRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                electroRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                electroRadButtonMouseExited(evt);
            }
        });
        electroRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                electroRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(electroRadButton);
        electroRadButton.setBounds(620, 340, 120, 33);

        geoRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        geoRadButton.setForeground(new java.awt.Color(252, 236, 214));
        geoRadButton.setText("Geo");
        geoRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        geoRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        geoRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                geoRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                geoRadButtonMouseExited(evt);
            }
        });
        geoRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geoRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(geoRadButton);
        geoRadButton.setBounds(780, 340, 120, 33);

        physicalRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        physicalRadButton.setForeground(new java.awt.Color(252, 236, 214));
        physicalRadButton.setText("Physical");
        physicalRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        physicalRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        physicalRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                physicalRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                physicalRadButtonMouseExited(evt);
            }
        });
        physicalRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                physicalRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(physicalRadButton);
        physicalRadButton.setBounds(1060, 340, 140, 33);

        cryoRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        cryoRadButton.setForeground(new java.awt.Color(252, 236, 214));
        cryoRadButton.setText("Cryo");
        cryoRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cryoRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        cryoRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cryoRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cryoRadButtonMouseExited(evt);
            }
        });
        cryoRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cryoRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(cryoRadButton);
        cryoRadButton.setBounds(780, 290, 120, 33);

        anemoRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        anemoRadButton.setForeground(new java.awt.Color(252, 236, 214));
        anemoRadButton.setText("Anemo");
        anemoRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        anemoRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        anemoRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                anemoRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                anemoRadButtonMouseExited(evt);
            }
        });
        anemoRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anemoRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(anemoRadButton);
        anemoRadButton.setBounds(910, 340, 120, 33);

        jLabel5.setFont(new java.awt.Font("HYWenHei-85W", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(241, 167, 84));
        jLabel5.setText("Preferred Elements");
        jLabel5.setToolTipText("");
        teamPage1.add(jLabel5);
        jLabel5.setBounds(620, 230, 380, 40);

        bowRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        bowRadButton.setForeground(new java.awt.Color(252, 236, 214));
        bowRadButton.setText("Bow");
        bowRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        bowRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        bowRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bowRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bowRadButtonMouseExited(evt);
            }
        });
        bowRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bowRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(bowRadButton);
        bowRadButton.setBounds(620, 530, 120, 33);

        polearmRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        polearmRadButton.setForeground(new java.awt.Color(252, 236, 214));
        polearmRadButton.setText("Polearm");
        polearmRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        polearmRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        polearmRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                polearmRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                polearmRadButtonMouseExited(evt);
            }
        });
        polearmRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polearmRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(polearmRadButton);
        polearmRadButton.setBounds(780, 480, 140, 33);

        catalystRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        catalystRadButton.setForeground(new java.awt.Color(252, 236, 214));
        catalystRadButton.setText("Catalyst");
        catalystRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        catalystRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        catalystRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                catalystRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                catalystRadButtonMouseExited(evt);
            }
        });
        catalystRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                catalystRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(catalystRadButton);
        catalystRadButton.setBounds(780, 530, 130, 33);

        claymoreRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        claymoreRadButton.setForeground(new java.awt.Color(252, 236, 214));
        claymoreRadButton.setText("Claymore");
        claymoreRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        claymoreRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        claymoreRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                claymoreRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                claymoreRadButtonMouseExited(evt);
            }
        });
        claymoreRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                claymoreRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(claymoreRadButton);
        claymoreRadButton.setBounds(960, 480, 150, 33);

        pyroRadButton.setFont(new java.awt.Font("HYWenHei-85W", 0, 22)); // NOI18N
        pyroRadButton.setForeground(new java.awt.Color(252, 236, 214));
        pyroRadButton.setText("Pyro");
        pyroRadButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pyroRadButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/radio1.png"))); // NOI18N
        pyroRadButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pyroRadButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pyroRadButtonMouseExited(evt);
            }
        });
        pyroRadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyroRadButtonActionPerformed(evt);
            }
        });
        teamPage1.add(pyroRadButton);
        pyroRadButton.setBounds(620, 290, 120, 33);

        jLabel6.setFont(new java.awt.Font("HYWenHei-85W", 0, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(241, 167, 84));
        jLabel6.setText("Preferred Weapon");
        jLabel6.setToolTipText("");
        teamPage1.add(jLabel6);
        jLabel6.setBounds(620, 420, 380, 40);

        jLabel7.setFont(new java.awt.Font("HYWenHei-85W", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(241, 167, 84));
        jLabel7.setText("(optional)");
        jLabel7.setToolTipText("");
        teamPage1.add(jLabel7);
        jLabel7.setBounds(970, 430, 90, 30);

        nextLabel.setFont(new java.awt.Font("HYWenHei-85W", 0, 24)); // NOI18N
        nextLabel.setForeground(new java.awt.Color(255, 255, 255));
        nextLabel.setText("Next");
        nextLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextLabelMouseExited(evt);
            }
        });
        teamPage1.add(nextLabel);
        nextLabel.setBounds(1100, 640, 60, 30);

        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/button1.png"))); // NOI18N
        nextButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nextButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nextButtonMouseExited(evt);
            }
        });
        teamPage1.add(nextButton);
        nextButton.setBounds(1000, 630, 247, 46);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/bg_teamguide.png"))); // NOI18N
        teamPage1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1280, 720);

        parentPanel.add(teamPage1, "card4");

        getContentPane().add(parentPanel);
        parentPanel.setBounds(0, 0, 1280, 720);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void profileButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_profileButtonMouseClicked

    private void profileButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseEntered
        //        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/profile2.png")));
        //        profileButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_profileButtonMouseEntered

    private void profileButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profileButtonMouseExited
        //        profileButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/profile1.png")));
        //        profileButton.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_profileButtonMouseExited

    private void exitButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseClicked
        int option = JOptionPane.showConfirmDialog(getContentPane(), "Are you sure you want to go back? Your changes won't be saved", "SELECT", JOptionPane.YES_NO_OPTION);
        if(option == JOptionPane.YES_OPTION){
            setVisible(false);
            dispose();
            new Home().setVisible(true);
        }
    }//GEN-LAST:event_exitButtonMouseClicked

    private void exitButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseEntered
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/exit2.png")));
        exitButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_exitButtonMouseEntered

    private void exitButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitButtonMouseExited
        exitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/exit1.png")));
        exitButton.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_exitButtonMouseExited

    private void nextButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseClicked
        //nextbuttonnnnnnnnn
    }//GEN-LAST:event_nextButtonMouseClicked

    private void nextButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseEntered
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/button2.png")));
        nextButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        nextLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_nextButtonMouseEntered

    private void nextButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextButtonMouseExited
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/button1.png")));
        nextButton.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        nextLabel.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_nextButtonMouseExited

    private void nextLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextLabelMouseClicked
//        nextlabelll
    }//GEN-LAST:event_nextLabelMouseClicked

    private void nextLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextLabelMouseEntered
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/button2.png")));
        nextButton.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        nextLabel.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_nextLabelMouseEntered

    private void nextLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextLabelMouseExited
        nextButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/App/image/button1.png")));
        nextButton.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        nextLabel.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_nextLabelMouseExited

    
    private void drawMouseEnteredRadioButton(String type, String component, JRadioButton radio){
        if(type.equals("elements")){
            if(elements.contains(component)){
                radio.setIcon(new ImageIcon("src/App/image/radio4.png"));
            }
            else{
                radio.setIcon(new ImageIcon("src/App/image/radio3.png"));
            }
        }
        else if(type.equals("weapons")){
            if(weapons.contains(component)){
                radio.setIcon(new ImageIcon("src/App/image/radio4.png"));
            }
            else{
                radio.setIcon(new ImageIcon("src/App/image/radio3.png"));
            }
        }
    }
    
    private void drawMouseExitedRadioButton(String type, String component, JRadioButton radio){
        if(type.equals("elements")){
            if(elements.contains(component)){
                radio.setIcon(new ImageIcon("src/App/image/radio2.png"));
            }
            else{
                radio.setIcon(new ImageIcon("src/App/image/radio1.png"));
            }
        }
        else if(type.equals("weapons")){
            if(weapons.contains(component)){
                radio.setIcon(new ImageIcon("src/App/image/radio2.png"));
            }
            else{
                radio.setIcon(new ImageIcon("src/App/image/radio1.png"));
            }
        }
            
    }
    
    private void radioButtonActionPerformed(String type, String component, JRadioButton radio){
        if(type.equals("elements")){
            if(!(elements.contains(component))){
                radio.setIcon(new ImageIcon("src/App/image/radio2.png"));
                elements.add(component);
            }
            else{
                radio.setIcon(new ImageIcon("src/App/image/radio1.png"));
                elements.remove(component);
            }  
        }
        else if(type.equals("weapons")){
            if(!(weapons.contains(component))){
                radio.setIcon(new ImageIcon("src/App/image/radio2.png"));
                weapons.add(component);
            }
            else{
                radio.setIcon(new ImageIcon("src/App/image/radio1.png"));
                weapons.remove(component);
            }
        }
        
    }
    
    
    private void pyroRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pyroRadButtonMouseEntered
        drawMouseEnteredRadioButton("elements", "pyro", pyroRadButton);
    }//GEN-LAST:event_pyroRadButtonMouseEntered

    private void pyroRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pyroRadButtonMouseExited
        drawMouseExitedRadioButton("elements", "pyro", pyroRadButton);
    }//GEN-LAST:event_pyroRadButtonMouseExited

    private void pyroRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyroRadButtonActionPerformed
        radioButtonActionPerformed("elements", "pyro", pyroRadButton);
    }//GEN-LAST:event_pyroRadButtonActionPerformed

    private void cryoRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cryoRadButtonActionPerformed
        radioButtonActionPerformed("elements", "cryo", cryoRadButton);
    }//GEN-LAST:event_cryoRadButtonActionPerformed

    private void cryoRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cryoRadButtonMouseEntered
        drawMouseEnteredRadioButton("elements", "cryo", cryoRadButton);
    }//GEN-LAST:event_cryoRadButtonMouseEntered

    private void cryoRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cryoRadButtonMouseExited
        drawMouseExitedRadioButton("elements", "cryo", cryoRadButton);
    }//GEN-LAST:event_cryoRadButtonMouseExited

    private void hydroRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hydroRadButtonActionPerformed
        radioButtonActionPerformed("elements", "hydro", hydroRadButton);
    }//GEN-LAST:event_hydroRadButtonActionPerformed

    private void hydroRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hydroRadButtonMouseEntered
        drawMouseEnteredRadioButton("elements", "hydro", hydroRadButton);
    }//GEN-LAST:event_hydroRadButtonMouseEntered

    private void hydroRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hydroRadButtonMouseExited
        drawMouseExitedRadioButton("elements", "hydro", hydroRadButton);
    }//GEN-LAST:event_hydroRadButtonMouseExited

    private void dendroRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dendroRadButtonActionPerformed
       radioButtonActionPerformed("elements", "dendro", dendroRadButton);
    }//GEN-LAST:event_dendroRadButtonActionPerformed

    private void dendroRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dendroRadButtonMouseEntered
        drawMouseEnteredRadioButton("elements", "dendro", dendroRadButton);
    }//GEN-LAST:event_dendroRadButtonMouseEntered

    private void dendroRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dendroRadButtonMouseExited
        drawMouseExitedRadioButton("elements", "dendro", dendroRadButton);
    }//GEN-LAST:event_dendroRadButtonMouseExited

    private void electroRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_electroRadButtonActionPerformed
        radioButtonActionPerformed("elements", "electro", electroRadButton);
    }//GEN-LAST:event_electroRadButtonActionPerformed

    private void electroRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electroRadButtonMouseEntered
        drawMouseEnteredRadioButton("elements", "electro", electroRadButton);
    }//GEN-LAST:event_electroRadButtonMouseEntered

    private void electroRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_electroRadButtonMouseExited
        drawMouseExitedRadioButton("elements", "electro", electroRadButton);
    }//GEN-LAST:event_electroRadButtonMouseExited

    private void geoRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geoRadButtonActionPerformed
        radioButtonActionPerformed("elements", "geo", geoRadButton);
    }//GEN-LAST:event_geoRadButtonActionPerformed

    private void geoRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geoRadButtonMouseEntered
        drawMouseEnteredRadioButton("elements", "geo", geoRadButton);
    }//GEN-LAST:event_geoRadButtonMouseEntered

    private void geoRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_geoRadButtonMouseExited
        drawMouseExitedRadioButton("elements", "geo", geoRadButton);
    }//GEN-LAST:event_geoRadButtonMouseExited

    private void anemoRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anemoRadButtonActionPerformed
        radioButtonActionPerformed("elements", "anemo", anemoRadButton);
    }//GEN-LAST:event_anemoRadButtonActionPerformed

    private void anemoRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anemoRadButtonMouseEntered
        drawMouseEnteredRadioButton("elements", "anemo", anemoRadButton);
    }//GEN-LAST:event_anemoRadButtonMouseEntered

    private void anemoRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_anemoRadButtonMouseExited
        drawMouseExitedRadioButton("elements", "anemo", anemoRadButton);
    }//GEN-LAST:event_anemoRadButtonMouseExited

    private void physicalRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_physicalRadButtonActionPerformed
        radioButtonActionPerformed("elements", "physical", physicalRadButton);
    }//GEN-LAST:event_physicalRadButtonActionPerformed

    private void physicalRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_physicalRadButtonMouseEntered
        drawMouseEnteredRadioButton("elements", "physical", physicalRadButton);
    }//GEN-LAST:event_physicalRadButtonMouseEntered

    private void physicalRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_physicalRadButtonMouseExited
        drawMouseExitedRadioButton("elements", "physical", physicalRadButton);
    }//GEN-LAST:event_physicalRadButtonMouseExited

    private void swordRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_swordRadButtonActionPerformed
        radioButtonActionPerformed("weapons", "sword", swordRadButton);
    }//GEN-LAST:event_swordRadButtonActionPerformed

    private void swordRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_swordRadButtonMouseEntered
        drawMouseEnteredRadioButton("weapons", "sword", swordRadButton);
    }//GEN-LAST:event_swordRadButtonMouseEntered

    private void swordRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_swordRadButtonMouseExited
        drawMouseExitedRadioButton("weapons", "sword", swordRadButton);
    }//GEN-LAST:event_swordRadButtonMouseExited

    private void polearmRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polearmRadButtonActionPerformed
        radioButtonActionPerformed("weapons", "polearm", polearmRadButton);
    }//GEN-LAST:event_polearmRadButtonActionPerformed

    private void polearmRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polearmRadButtonMouseEntered
        drawMouseEnteredRadioButton("weapons", "polearm", polearmRadButton);
    }//GEN-LAST:event_polearmRadButtonMouseEntered

    private void polearmRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_polearmRadButtonMouseExited
        drawMouseExitedRadioButton("weapons", "polearm", polearmRadButton);
    }//GEN-LAST:event_polearmRadButtonMouseExited

    private void claymoreRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_claymoreRadButtonActionPerformed
        radioButtonActionPerformed("weapons", "claymore", claymoreRadButton);
    }//GEN-LAST:event_claymoreRadButtonActionPerformed

    private void claymoreRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claymoreRadButtonMouseEntered
       drawMouseEnteredRadioButton("weapons", "claymore", claymoreRadButton);
    }//GEN-LAST:event_claymoreRadButtonMouseEntered

    private void claymoreRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_claymoreRadButtonMouseExited
        drawMouseExitedRadioButton("weapons", "claymore", claymoreRadButton);
    }//GEN-LAST:event_claymoreRadButtonMouseExited

    private void bowRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bowRadButtonActionPerformed
        radioButtonActionPerformed("weapons", "bow", bowRadButton);
    }//GEN-LAST:event_bowRadButtonActionPerformed

    private void bowRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bowRadButtonMouseEntered
        drawMouseEnteredRadioButton("weapons", "bow", bowRadButton);
    }//GEN-LAST:event_bowRadButtonMouseEntered

    private void bowRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bowRadButtonMouseExited
        drawMouseExitedRadioButton("weapons", "bow", bowRadButton);
    }//GEN-LAST:event_bowRadButtonMouseExited

    private void catalystRadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_catalystRadButtonActionPerformed
        radioButtonActionPerformed("weapons", "catalyst", catalystRadButton);
    }//GEN-LAST:event_catalystRadButtonActionPerformed

    private void catalystRadButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalystRadButtonMouseEntered
        drawMouseEnteredRadioButton("weapons", "catalyst", catalystRadButton);
    }//GEN-LAST:event_catalystRadButtonMouseEntered

    private void catalystRadButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_catalystRadButtonMouseExited
        drawMouseExitedRadioButton("weapons", "catalyst", catalystRadButton);
    }//GEN-LAST:event_catalystRadButtonMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeamGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeamGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeamGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeamGuide.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeamGuide().setVisible(true);
//                SwingUtilities.invokeLater(TeamGuide::new);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton anemoRadButton;
    private javax.swing.JRadioButton bowRadButton;
    private javax.swing.JRadioButton catalystRadButton;
    private javax.swing.JRadioButton claymoreRadButton;
    private javax.swing.JPanel clonePanelContainer;
    private javax.swing.JRadioButton cryoRadButton;
    private javax.swing.JRadioButton dendroRadButton;
    private javax.swing.JRadioButton electroRadButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JPanel enemiesPane;
    private javax.swing.JLabel exitButton;
    private javax.swing.JRadioButton geoRadButton;
    private javax.swing.JRadioButton hydroRadButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton modeEnemyOnly;
    private javax.swing.JRadioButton modeSpiralAbyss;
    private javax.swing.JLabel nextButton;
    private javax.swing.JLabel nextLabel;
    private javax.swing.JPanel parentPanel;
    private javax.swing.JRadioButton physicalRadButton;
    private javax.swing.JRadioButton polearmRadButton;
    private javax.swing.JLabel profileButton;
    private javax.swing.JRadioButton pyroRadButton;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JRadioButton swordRadButton;
    private javax.swing.JPanel teamPage1;
    private javax.swing.JLabel usernameLabel;
    // End of variables declaration//GEN-END:variables
}
